# Identificación del proyecto
sonar.projectKey=PaulaMartinezDevOps_DevOps_PruebaTecnica
sonar.organization=paulamartinezdevops

# Información del proyecto
sonar.projectName=DevOps_PruebaTecnica
sonar.projectVersion=1.0

# Ubicación del código
sonar.sources=app

# Ubicación de pruebas
sonar.tests=tests

# Lenguaje
sonar.language=py

# Encoding
sonar.sourceEncoding=UTF-8